version: "3.9"

services:
  fastapi:
    build: ./src
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    networks:
      - app-net
    depends_on:
      - postgres

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
          
  postgres:
    image: postgres:16
    env_file:
      - "./src/.env"
    ports:
      - "5432:5432"
    networks:
      - app-net

volumes:
  app-data:
    driver: local

networks:
  app-net:
    driver: bridge
