version: "3.9"

services:
  fastapi:
    build: ./src
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    networks:
      - app-net
    depends_on:
      - postgres

  ml:
    build: ./ml
    container_name: ml
    ports:
      - "8001:8001"
    volumes:
      - ./configs:/ml/configs
    networks:
      - app-net
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    env_file:
      - "./src/.env"
    ports:
      - "5432:5432"
    networks:
      - app-net

volumes:
  app-data:
    driver: local

networks:
  app-net:
    driver: bridge
