version: "3.9"

services:
  fastapi:
    build: ./src
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    networks:
      - app-net
    depends_on:
      - postgres

  ml:
    build: ./ml
    container_name: ml
    ports:
      - "8001:8001"
    volumes:
      - ./configs:/ml/configs
    networks:
      - app-net
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    env_file:
      - "./src/.env"
    ports:
      - "5432:5432"
    networks:
      - app-net

  backend-go:
    build:
      context: backend
    container_name: backend-go
    ports:
      - "8383:8383"
    volumes:
      - ./data:/data
    networks:
      - app-net
    depends_on:
      - postgres

volumes:
  app-data:
    driver: local

networks:
  app-net:
    driver: bridge
