version: "3.9"

services:
  fastapi:
    build: ./src
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    networks:
      - app-net

volumes:
  app-data:
    driver: local

networks:
  app-net:
    driver: bridge
